# Generated by Django 2.0.4 on 2018-06-18 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', validators=[django.core.validators.MinLengthValidator(200)]),
        ),
    ]
