# Generated by Django 2.0.4 on 2018-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180618_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, max_length=200, upload_to=''),
        ),
    ]
