# Generated by Django 2.0.4 on 2018-07-05 08:09

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180705_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='Ex: 127,35', max_length=500, validators=[blog.models.lnglat_validator]),
        ),
    ]
