# Generated by Django 2.0.4 on 2018-06-14 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_auto_20180612_0601'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(choices=[('A', 'A서버'), ('B', 'B서버'), ('C', 'C서버')], max_length=10)),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='ip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='gamuser',
            unique_together={('server_name', 'username')},
        ),
    ]
