# Generated by Django 2.0.4 on 2018-06-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_auto_20180614_0637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamUser',
            new_name='GameUser',
        ),
    ]
